### ISSUE TITLE
(node:27437) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFileSync' of undefined

### ISSUE THREAD

**Issue by pierrenel** [dosyago/22120#26]
Tried node 11 and 12, and also tried a clone of the repo, and via npx - but I get this message when I try to switch over to save mode:

`(node:27437) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFileSync' of undefined`

Here's the whole enchilada: 

```/Code
❯ npx archivist1
npx: installed 76 in 17.841s
Args usage: <server_port> <save|serve> <chrome_port> <library_path>
Running in node...
Importing dependencies...
Attempting to shut running chrome...
Running chrome shut down.
Waiting 1 second...
Removing 22120's existing temporary browser cache if it exists...
Launching library server...
Library server started.
Waiting 1 second...
{"server_up":{"upAt":"2020-02-09T06:18:06.414Z","port":22120}}
Launching chrome...
(node:27437) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFileSync' of undefined
    at K (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:321:11456)
    at Object.changeMode (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:321:7502)
    at /Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:321:13528
    at s.handle_request (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:128:783)
    at s (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:121:879)
    at p.dispatch (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:121:901)
    at s.handle_request (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:128:783)
    at /Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:114:2530
    at Function.v.process_params (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:114:3433)
    at g (/Users/pierre/.npm/_npx/27437/lib/node_modules/archivist1/22120.js:114:2473)
(node:27437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27437) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
(node:27437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by pierrenel** [comment]
Ah! It turns out I _really_ have to quit Chrome before firing it up, I'll set up a PR for the docs.
